# Generated by Django 5.2.1 on 2025-08-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('famille', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_negatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motif')),
                ('nb_negatif', models.IntegerField(default=0, verbose_name='Nombre')),
                ('date', models.DateField(auto_now=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famille.enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Point_positif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motif')),
                ('nb_positif', models.IntegerField(default=0, verbose_name='Nombre')),
                ('date', models.DateField(auto_now=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famille.enfant')),
            ],
        ),
    ]
