# Generated by Django 5.2.5 on 2025-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaremePointNegatif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.CharField(max_length=1000)),
                ("points", models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="BaremePointPositif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.CharField(max_length=1000)),
                ("points", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="BaremeRecompense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                ("valeur_euros", models.CharField(max_length=200)),
                ("valeur_temps", models.CharField(max_length=200)),
            ],
        ),
    ]
