# Generated by Django 5.2.5 on 2025-08-15 21:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0003_enfant_user"),
        ("points", "0002_baremepointnegatif_baremepointpositif_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point_positif",
            name="enfant",
        ),
        migrations.CreateModel(
            name="PointNegatif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif2",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Motif"
                    ),
                ),
                ("nb_negatif", models.IntegerField(default=0, verbose_name="Nombre")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "enfant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="famille.enfant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointPositif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif1",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Motif"
                    ),
                ),
                ("nb_positif", models.IntegerField(default=0, verbose_name="Nombre")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "enfant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="famille.enfant"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Point_negatif",
        ),
        migrations.DeleteModel(
            name="Point_positif",
        ),
    ]
