# Generated by Django 5.2.5 on 2025-10-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0004_alter_enfant_famille"),
        ("points", "0003_remove_point_positif_enfant_pointnegatif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baremepointnegatif",
            name="famille",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="famille.famille",
            ),
        ),
        migrations.AddField(
            model_name="baremepointpositif",
            name="famille",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="famille.famille",
            ),
        ),
        migrations.AddField(
            model_name="baremerecompense",
            name="famille",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="famille.famille",
            ),
        ),
    ]
