# Generated by Django 5.2.5 on 2025-08-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="famille",
            options={},
        ),
        migrations.RemoveField(
            model_name="famille",
            name="is_first_login",
        ),
        migrations.RemoveField(
            model_name="famille",
            name="user",
        ),
        migrations.AlterField(
            model_name="famille",
            name="nom",
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("parent", "Parent"), ("enfant", "Enfant")],
                        max_length=10,
                    ),
                ),
                (
                    "famille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="famille.famille",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
