# Generated by Django 5.2.5 on 2025-08-12 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "famille",
            "0002_alter_famille_options_remove_famille_is_first_login_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enfant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profil_enfant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
