# Generated by Django 5.2.5 on 2025-09-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0003_enfant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enfant",
            name="famille",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enfants",
                to="famille.famille",
            ),
        ),
    ]
