# Generated by Django 5.0 on 2024-01-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enfant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=200)),
                ("solde_points", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Point_negatif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_negatifs", models.IntegerField(default=0)),
                ("date_points_negatifs", models.DateTimeField(verbose_name="date")),
                (
                    "enfant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="points_app.enfant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Point_positif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_positifs", models.IntegerField(default=0)),
                ("date_points_positifs", models.DateTimeField(verbose_name="date")),
                (
                    "enfant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="points_app.enfant",
                    ),
                ),
            ],
        ),
    ]
