# Generated by Django 5.0 on 2024-01-17 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="point_negatif",
            old_name="date_points_negatifs",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="point_positif",
            old_name="date_points_positifs",
            new_name="date",
        ),
    ]
