# Generated by Django 5.0 on 2024-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0002_rename_date_points_negatifs_point_negatif_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point_negatif",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="point_positif",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
