# Generated by Django 5.0 on 2024-01-17 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0003_alter_point_negatif_date_alter_point_positif_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="point_negatif",
            old_name="points_negatifs",
            new_name="nb",
        ),
        migrations.RenameField(
            model_name="point_positif",
            old_name="points_positifs",
            new_name="nb",
        ),
    ]
