# Generated by Django 5.0.1 on 2024-01-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0004_rename_points_negatifs_point_negatif_nb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="point_negatif",
            name="motif",
            field=models.CharField(default="non renseigné", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="point_positif",
            name="motif",
            field=models.CharField(default="non renseigné", max_length=1000),
            preserve_default=False,
        ),
    ]
