# Generated by Django 5.0.1 on 2024-01-25 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0005_point_negatif_motif_point_positif_motif"),
    ]

    operations = [
        migrations.RenameField(
            model_name="point_negatif",
            old_name="motif",
            new_name="motif2",
        ),
        migrations.RenameField(
            model_name="point_negatif",
            old_name="nb",
            new_name="nb_negatif",
        ),
        migrations.RenameField(
            model_name="point_positif",
            old_name="motif",
            new_name="motif1",
        ),
        migrations.RenameField(
            model_name="point_positif",
            old_name="nb",
            new_name="nb_positif",
        ),
    ]
