# Generated by Django 5.0.1 on 2024-01-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0006_rename_motif_point_negatif_motif2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point_negatif",
            name="motif2",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="point_positif",
            name="motif1",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
