# Generated by Django 5.0.1 on 2024-01-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0007_alter_point_negatif_motif2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point_positif",
            name="nb_positif",
            field=models.IntegerField(default=0, verbose_name="Nombre"),
        ),
    ]
