# Generated by Django 5.0.1 on 2024-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points_app", "0008_alter_point_positif_nb_positif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point_negatif",
            name="motif2",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Motif"
            ),
        ),
        migrations.AlterField(
            model_name="point_negatif",
            name="nb_negatif",
            field=models.IntegerField(default=0, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="point_positif",
            name="motif1",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Motif"
            ),
        ),
    ]
